version = "2"

[run]
build-tags = ["goolm"]

[linters]
default = "all"
disable = ["depguard", "exhaustruct", "noctx", "noinlineerr", "mnd", "perfsprint", "wsl"]
exclusions = { presets = ["std-error-handling"] }
settings.ireturn = { allow = ["error", "stdlib", "Plugin"] }
settings.lll = { tab-width = 4 }
settings.revive.enable-all-rules = true
settings.revive.rules = [
    { name = "add-constant", disabled = true },
    { name = "cognitive-complexity", disabled = true },
    { name = "identical-switch-branches", disabled = true },
    { name = "line-length-limit", disabled = true },
    { name = "max-public-structs", disabled = true },
    { name = "var-naming", disabled = true }
]
settings.tagliatelle.case.rules = { json = "snake", toml = "snake"}
settings.varnamelen.ignore-names = ["err", "ok"]

[formatters]
enable = ["gci", "gofmt", "gofumpt", "goimports", "golines", "swaggo"]
settings = { golines = { max-len = 120, tab-len = 4 } }
