version: "2"
run: { build-tags: [goolm] }
linters: {
  default: all,
  disable: [depguard, exhaustruct, mnd, noinlineerr, tagliatelle, wsl],
  settings: {
    govet: { enable-all: true },
    ireturn: { allow: [anon, error, empty, stdlib, Plugin, Database] },
    lll: { tab-width: 2 },
    revive: {
      enable-all-rules: true,
      rules: [
        { name: add-constant, disabled: true },
        { name: cognitive-complexity, disabled: true },
        { name: cyclomatic, disabled: true },
        { name: line-length-limit, arguments: [120] },
        { name: max-public-structs, disabled: true },
      ],
    },
    varnamelen: {
      ignore-type-assert-ok: true,
      ignore-map-index-ok: true,
      ignore-chan-recv-ok: true,
      ignore-names: [err, ok],
    },
  },
  exclusions: { warn-unused: false, paths: [internal/cache] },
}
formatters: {
  enable: [gci, gofmt, gofumpt, goimports, golines, swaggo],
  settings: { golines: { max-len: 120, tab-len: 2 } },
}
