package rvapi

// Code generated by Typescript and suffering; DO NOT EDIT.

import "time"

// User.
type User struct {
	Status        *UserStatus        `json:"status"`
	Bot           *BotInformation    `json:"bot"`
	Relationship  RelationshipStatus `json:"relationship"`
	ID            string             `json:"_id"`
	Username      string             `json:"username"`
	Discriminator string             `json:"discriminator"`
	DisplayName   string             `json:"display_name"`
	Avatar        *File              `json:"avatar"`
	Relations     []Relationship     `json:"relations,omitempty"`
	Badges        uint64             `json:"badges"`
	Flags         uint64             `json:"flags"`
	Privileged    bool               `json:"privileged"`
	Online        bool               `json:"online"`
}

// CDN file.
type CDNFile struct {
	Metadata    Metadata `json:"metadata"`
	ID          string   `json:"id"`
	Tag         string   `json:"tag"`
	Filename    string   `json:"filename"`
	ContentType string   `json:"content_type"`
	Size        int      `json:"size"`
}

// File.
type File struct {
	Metadata    Metadata `json:"metadata"`
	ID          string   `json:"_id"`
	Tag         string   `json:"tag"`
	Filename    string   `json:"filename"`
	ContentType string   `json:"content_type"`
	Size        int      `json:"size"`
}

// Relationship entry indicating current status with other user.
type Relationship struct {
	ID     string             `json:"_id"`
	Status RelationshipStatus `json:"status"`
}

// UserStatus is a user's active status.
type UserStatus struct {
	Text     string   `json:"text"`
	Presence Presence `json:"presence"`
}

// BotInformation for if the user is a bot.
type BotInformation struct {
	Owner string `json:"owner"`
}

// Representation of a single permission override as it appears on models and in the database.
type OverrideField struct {
	Allow Permission `json:"a"`
	Deny  Permission `json:"d"`
}

// Bot.
type Bot struct {
	ID              string `json:"_id"`
	Owner           string `json:"owner"`
	Token           string `json:"token"`
	InteractionsURL string `json:"interactions_url"`
	TermsURL        string `json:"terms_of_service_url"`
	PrivacyURL      string `json:"privacy_policy_url"`
	Flags           uint64 `json:"flags"`
	Public          bool   `json:"public"`
	Analytics       bool   `json:"analytics"`
	Discoverable    bool   `json:"discoverable"`
}

// Message.
type Message struct {
	Edited       time.Time           `json:"edited"`
	Member       *Member             `json:"member"`
	Reactions    map[string][]string `json:"reactions"`
	System       *SystemMessage      `json:"system"`
	Masquerade   *Masquerade         `json:"masquerade"`
	Webhook      *MessageWebhook     `json:"webhook"`
	User         *User               `json:"user"`
	Interactions *Interactions       `json:"interactions"`
	Content      string              `json:"content"`
	Author       string              `json:"author"`
	Channel      string              `json:"channel"`
	Nonce        string              `json:"nonce"`
	ID           string              `json:"_id"`
	Attachments  []File              `json:"attachments,omitempty"`
	Embeds       []Embed             `json:"embeds,omitempty"`
	Mentions     []string            `json:"mentions,omitempty"`
	RoleMentions []string            `json:"role_mentions,omitempty"`
	Replies      []string            `json:"replies,omitempty"`
	Flags        uint64              `json:"flags"`
	Pinned       bool                `json:"pinned"`
}

// Server Member.
type Member struct {
	ID       MemberCompositeKey `json:"_id"`
	JoinedAt time.Time          `json:"joined_at"`
	Timeout  time.Time          `json:"timeout"`
	Avatar   *File              `json:"avatar"`
	Nickname *string            `json:"nickname"`
	Roles    []string           `json:"roles,omitempty"`
}

// Composite primary key consisting of server and user id.
type MemberCompositeKey struct {
	Server string `json:"server"`
	User   string `json:"user"`
}

// Information about the webhook bundled with Message.
type MessageWebhook struct {
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}

// Image.
type Image struct {
	URL    string    `json:"url"`
	Size   ImageSize `json:"size"`
	Width  int       `json:"width"`
	Height int       `json:"height"`
}

// Video.
type Video struct {
	URL    string `json:"url"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}

// Information to guide interactions on this message.
type Interactions struct {
	Reactions         []string `json:"reactions,omitempty"`
	RestrictReactions bool     `json:"restrict_reactions"`
}

// Name and / or avatar override information.
type Masquerade struct {
	Name   string `json:"name,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	Colour string `json:"colour,omitempty"`
}

// Message to send.
type DataMessageSend struct {
	Masquerade   *Masquerade     `json:"masquerade,omitempty"`
	Interactions *Interactions   `json:"interactions,omitempty"`
	Content      string          `json:"content"`
	Attachments  []string        `json:"attachments,omitempty"`
	Replies      []ReplyIntent   `json:"replies,omitempty"`
	Embeds       []SendableEmbed `json:"embeds,omitempty"`
	Flags        uint64          `json:"flags,omitempty"`
}

// What this message should reply to and how.
type ReplyIntent struct {
	ID              string `json:"id"`
	Mention         bool   `json:"mention"`
	FailIfNotExists bool   `json:"fail_if_not_exists"`
}

// Representation of a text embed before it is sent.
type SendableEmbed struct {
	IconURL     *string `json:"icon_url,omitempty"`
	URL         *string `json:"url,omitempty"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Media       *string `json:"media,omitempty"`
	Colour      *string `json:"colour,omitempty"`
}

// Changes to make to message.
type DataEditMessage struct {
	Content string          `json:"content"`
	Embeds  []SendableEmbed `json:"embeds,omitempty"`
}

// Options for bulk deleting messages.
type OptionsBulkDelete struct {
	IDs []string `json:"ids,omitempty"`
}

// Representation of a single permission override.
type Override struct {
	Allow Permission `json:"allow"`
	Deny  Permission `json:"deny"`
}

// Server.
type Server struct {
	Roles              map[string]Role       `json:"roles"`
	SystemMessages     SystemMessageChannels `json:"system_messages"`
	ID                 string                `json:"_id"`
	Owner              string                `json:"owner"`
	Name               string                `json:"name"`
	Description        string                `json:"description"`
	Channels           []string              `json:"channels,omitempty"`
	Categories         []Category            `json:"categories,omitempty"`
	Icon               File                  `json:"icon"`
	Banner             File                  `json:"banner"`
	DefaultPermissions Permission            `json:"default_permissions"`
	Flags              uint64                `json:"flags"`
	NSFW               bool                  `json:"nsfw"`
	Analytics          bool                  `json:"analytics"`
	Discoverable       bool                  `json:"discoverable"`
}

// Channel category.
type Category struct {
	ID       string   `json:"id"`
	Title    string   `json:"title"`
	Channels []string `json:"channels,omitempty"`
}

// System message channel assignments.
type SystemMessageChannels struct {
	UserJoined string `json:"user_joined"`
	UserLeft   string `json:"user_left"`
	UserKicked string `json:"user_kicked"`
	UserBanned string `json:"user_banned"`
}

// Role.
type Role struct {
	Name        string        `json:"name"`
	Colour      string        `json:"colour"`
	Permissions OverrideField `json:"permissions"`
	Rank        int           `json:"rank"`
	Hoist       bool          `json:"hoist"`
}

// Emoji.
type Emoji struct {
	ID        string      `json:"_id"`
	Parent    EmojiParent `json:"parent"`
	CreatorID string      `json:"creator_id"`
	Name      string      `json:"name"`
	Animated  bool        `json:"animated"`
	NSFW      bool        `json:"nsfw"`
}

// Channel Unread.
type ChannelUnread struct {
	ID       ChannelCompositeKey `json:"_id"`
	LastID   string              `json:"last_id"`
	Mentions []string            `json:"mentions,omitempty"`
}

// Composite primary key consisting of channel and user id.
type ChannelCompositeKey struct {
	Channel string `json:"channel"`
	User    string `json:"user"`
}

// Possible relationships you can have with a user.
type RelationshipStatus string

const (
	RelationshipNone         RelationshipStatus = "None"
	RelationshipUser         RelationshipStatus = "User"
	RelationshipFriend       RelationshipStatus = "Friend"
	RelationshipOutgoing     RelationshipStatus = "Outgoing"
	RelationshipIncoming     RelationshipStatus = "Incoming"
	RelationshipBlocked      RelationshipStatus = "Blocked"
	RelationshipBlockedOther RelationshipStatus = "BlockedOther"
)

// Metadata represents different file/content metadata types.
type Metadata struct {
	Width  *int   `json:"width,omitempty"`
	Height *int   `json:"height,omitempty"`
	Type   string `json:"type"`
}

// Presence indicates a user’s online state.
type Presence string

const (
	PresenceOnline    Presence = "Online"
	PresenceIdle      Presence = "Idle"
	PresenceFocus     Presence = "Focus"
	PresenceBusy      Presence = "Busy"
	PresenceInvisible Presence = "Invisible"
)

// FieldsUser defines which user fields can be updated.
type FieldsUser string

const (
	FieldsUserAvatar         FieldsUser = "Avatar"
	FieldsUserStatusText     FieldsUser = "StatusText"
	FieldsUserStatusPresence FieldsUser = "StatusPresence"
	FieldsUserProfileContent FieldsUser = "ProfileContent"
	FieldsUserProfileBg      FieldsUser = "ProfileBackground"
	FieldsUserDisplayName    FieldsUser = "DisplayName"
	FieldsUserInternal       FieldsUser = "Internal"
)

// Channel represents all channel types.
type Channel struct {
	User            *string                  `json:"user,omitempty"`
	Active          *bool                    `json:"active,omitempty"`
	LastMessageID   *string                  `json:"last_message_id,omitempty"`
	Name            string                   `json:"name,omitempty"`
	Owner           *string                  `json:"owner,omitempty"`
	Description     *string                  `json:"description,omitempty"`
	Icon            *File                    `json:"icon,omitempty"`
	Permissions     *Permission              `json:"permissions,omitempty"`
	NSFW            *bool                    `json:"nsfw,omitempty"`
	Server          *string                  `json:"server,omitempty"`
	DefaultPerms    *OverrideField           `json:"default_permissions,omitempty"`
	RolePermissions map[string]OverrideField `json:"role_permissions,omitempty"`
	ChannelType     ChannelType              `json:"channel_type"`
	ID              string                   `json:"_id"`
	Recipients      []string                 `json:"recipients,omitempty"`
}

type ChannelType string

const (
	ChannelTypeSavedMessages ChannelType = "SavedMessages"
	ChannelTypeText          ChannelType = "TextChannel"
	ChannelTypeVoice         ChannelType = "VoiceChannel"
	ChannelTypeDM            ChannelType = "DirectMessage"
	ChannelTypeGroup         ChannelType = "Group"
)

// FieldsBot describes updatable bot fields.
type FieldsBot string

const (
	FieldsBotToken        FieldsBot = "Token"
	FieldsBotInteractions FieldsBot = "InteractionsURL"
)

// FieldsChannel describes updatable channel fields.
type FieldsChannel string

const (
	FieldsChannelDescription  FieldsChannel = "Description"
	FieldsChannelIcon         FieldsChannel = "Icon"
	FieldsChannelDefaultPerms FieldsChannel = "DefaultPermissions"
)

// SystemMessage represents events generated by the system.
type SystemMessage struct {
	Content *string `json:"content,omitempty"`
	ID      *string `json:"id,omitempty"`
	By      *string `json:"by,omitempty"`
	From    *string `json:"from,omitempty"`
	To      *string `json:"to,omitempty"`
	Name    *string `json:"name,omitempty"`
	Type    string  `json:"type"`
}

// Embed represents embedded rich content.
type Embed struct {
	URL         *string    `json:"url,omitempty"`
	OriginalURL *string    `json:"original_url,omitempty"`
	Special     *Special   `json:"special,omitempty"`
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	Image       *Image     `json:"image,omitempty"`
	Video       *Video     `json:"video,omitempty"`
	SiteName    *string    `json:"site_name,omitempty"`
	IconURL     *string    `json:"icon_url,omitempty"`
	Colour      *string    `json:"colour,omitempty"`
	Width       *int       `json:"width,omitempty"`
	Height      *int       `json:"height,omitempty"`
	Size        *ImageSize `json:"size,omitempty"`
	Media       *File      `json:"media,omitempty"`
	Type        string     `json:"type"`
}

// Special describes special remote content (like GIF, YouTube, etc.)
type Special struct {
	ID          *string `json:"id,omitempty"`
	Timestamp   *string `json:"timestamp,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	AlbumID     *string `json:"album_id,omitempty"`
	TrackID     *string `json:"track_id,omitempty"`
	Type        string  `json:"type"`
}

// ImageSize.
type ImageSize string

const (
	ImageSizeLarge   ImageSize = "Large"
	ImageSizePreview ImageSize = "Preview"
)

// EmojiParent represents emoji scoping.
type EmojiParent struct {
	Type string `json:"type"`
	ID   string `json:"id,omitempty"`
}

// Bulk event wraps multiple events into a single payload.
type BulkEvent struct {
	Type string   `json:"type"` // "Bulk"
	V    [][]byte `json:"v"`    // slice of other events
}

// Pong response to Ping.
type PongEvent struct {
	Type string `json:"type"` // "Pong"
	Data int64  `json:"data"`
}

// Ready event: provides initial data snapshot.
type ReadyEvent struct {
	Type           string          `json:"type"` // "Ready"
	Users          []User          `json:"users,omitempty"`
	Servers        []Server        `json:"servers,omitempty"`
	Channels       []Channel       `json:"channels,omitempty"`
	Members        []Member        `json:"members,omitempty"`
	Emojis         []Emoji         `json:"emojis,omitempty"`
	ChannelUnreads []ChannelUnread `json:"channel_unreads,omitempty"`
}

// Incoming message.
type MessageEvent struct {
	Type    string `json:"type"` // "Message"
	Message        //nolint:embeddedstructfieldcheck
}

// Message update (partial).
type MessageUpdateEvent struct {
	Type    string  `json:"type"` // "MessageUpdate"
	ID      string  `json:"id"`
	Channel string  `json:"channel"`
	Data    Message `json:"data"`
}

// Message deleted.
type MessageDeleteEvent struct {
	Type    string `json:"type"` // "MessageDelete"
	ID      string `json:"id"`
	Channel string `json:"channel"`
}

// BaseEvent provides the common "type" field.
type BaseEvent struct {
	Type string `json:"type"`
}

// Permission type.
type Permission uint64

// Individual permission flags.
const (
	PermissionManageChannel       Permission = 1 << 0  // Manage the channel or channels on the server
	PermissionManageServer        Permission = 1 << 1  // Manage the server
	PermissionManagePermissions   Permission = 1 << 2  // Manage permissions on servers or channels
	PermissionManageRole          Permission = 1 << 3  // Manage roles on server
	PermissionManageCustomization Permission = 1 << 4  // Manage emoji on servers
	PermissionKickMembers         Permission = 1 << 6  // Kick other members below their ranking
	PermissionBanMembers          Permission = 1 << 7  // Ban other members below their ranking
	PermissionTimeoutMembers      Permission = 1 << 8  // Timeout other members below their ranking
	PermissionAssignRoles         Permission = 1 << 9  // Assign roles to members below their ranking
	PermissionChangeNickname      Permission = 1 << 10 // Change own nickname
	PermissionManageNicknames     Permission = 1 << 11 // Change or remove other's nicknames below their ranking
	PermissionChangeAvatar        Permission = 1 << 12 // Change own avatar
	PermissionRemoveAvatars       Permission = 1 << 13 // Remove other's avatars below their ranking
	PermissionViewChannel         Permission = 1 << 20 // View a channel
	PermissionReadMessageHistory  Permission = 1 << 21 // Read a channel's past message history
	PermissionSendMessage         Permission = 1 << 22 // Send a message in a channel
	PermissionManageMessages      Permission = 1 << 23 // Delete messages in a channel
	PermissionManageWebhooks      Permission = 1 << 24 // Manage webhook entries on a channel
	PermissionInviteOthers        Permission = 1 << 25 // Create invites to this channel
	PermissionSendEmbeds          Permission = 1 << 26 // Send embedded content in this channel
	PermissionUploadFiles         Permission = 1 << 27 // Send attachments and media in this channel
	PermissionMasquerade          Permission = 1 << 28 // Masquerade messages using custom nickname and avatar
	PermissionReact               Permission = 1 << 29 // React to messages with emojis
	PermissionConnect             Permission = 1 << 30 // Connect to a voice channel
	PermissionSpeak               Permission = 1 << 31 // Speak in a voice call
	PermissionVideo               Permission = 1 << 32 // Share video in a voice call
	PermissionMuteMembers         Permission = 1 << 33 // Mute other members with lower ranking in a voice call
	PermissionDeafenMembers       Permission = 1 << 34 // Deafen other members with lower ranking in a voice call
	PermissionMoveMembers         Permission = 1 << 35 // Move members between voice channels
	PermissionAll                 Permission = 0x000F_FFFF_FFFF_FFFF
	PermissionSet1                Permission = PermissionSet3 | PermissionSendMessage |
		PermissionManageChannel | PermissionConnect | PermissionSendEmbeds | PermissionInviteOthers |
		PermissionUploadFiles
	PermissionSet2 Permission = PermissionSet1 | PermissionChangeNickname | PermissionChangeAvatar
	PermissionSet3 Permission = PermissionViewChannel | PermissionReadMessageHistory
)

// Individual permission names.
var PermissionNames = map[Permission]string{ //nolint:gochecknoglobals
	PermissionManageChannel:       "Manage Channel",
	PermissionManageServer:        "Manage Server",
	PermissionManagePermissions:   "Manage Permissions",
	PermissionManageRole:          "Manage Role",
	PermissionManageCustomization: "Manage Customization",
	PermissionKickMembers:         "Kick Members",
	PermissionBanMembers:          "Ban Members",
	PermissionTimeoutMembers:      "Timeout Members",
	PermissionAssignRoles:         "Assign Roles",
	PermissionChangeNickname:      "Change Nickname",
	PermissionManageNicknames:     "Manage Nicknames",
	PermissionChangeAvatar:        "Change Avatar",
	PermissionRemoveAvatars:       "Remove Avatars",
	PermissionViewChannel:         "View Channel",
	PermissionReadMessageHistory:  "Read Message History",
	PermissionSendMessage:         "Send Message",
	PermissionManageMessages:      "Manage Messages",
	PermissionManageWebhooks:      "Manage Webhooks",
	PermissionInviteOthers:        "Invite Others",
	PermissionSendEmbeds:          "Send Embeds",
	PermissionUploadFiles:         "Upload Files",
	PermissionMasquerade:          "Masquerade",
	PermissionReact:               "React",
	PermissionConnect:             "Connect",
	PermissionSpeak:               "Speak",
	PermissionVideo:               "Video",
	PermissionMuteMembers:         "Mute Members",
	PermissionDeafenMembers:       "Deafen Members",
	PermissionMoveMembers:         "Move Members",
}
